# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1440530365);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1440530005);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1440530245);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1440530125);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150807051213");
user_pref("browser.slowStartup.averageTime", 2455);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150807051213");
user_pref("browser.startup.homepage_override.mstone", "38.2.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1440616284947");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1440529946747");
user_pref("datareporting.policy.firstRunTime", "1440529884947");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.firstPaint", 1301);
user_pref("datareporting.sessions.current.main", 130);
user_pref("datareporting.sessions.current.sessionRestored", 1408);
user_pref("datareporting.sessions.current.startTime", "1440531187351");
user_pref("datareporting.sessions.current.totalTime", 31);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1440529883188,\"a\":12,\"t\":574,\"c\":true,\"m\":121,\"fp\":3398,\"sr\":3553}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.2.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1440530365);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.2.0");
user_pref("extensions.lastPlatformVersion", "38.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.2.0\",\"st\":1439454255000,\"mt\":1438939306000}}}");
user_pref("gecko.buildID", "20150807051213");
user_pref("gecko.mstone", "38.2.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1440529947);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150807051213");
user_pref("media.gmp-manager.lastCheck", 1440529947);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1440531187);
user_pref("toolkit.telemetry.previousBuildID", "20150807051213");
